# Site settings
title: wenhaiz's blog
default_author: wenhaiz
description: "安卓小开发仔"  # used in site head

# register on google analytics and replace this token
google_analytics: UA-106126503-1
# disque comments are broken if you send http:// along with url, this url is same as the one given on disqus
# Deleting the value would remove it from footer.
# disqus_url: shikherverma.com
# disqus_id: shikherverma
# register on feedburner and replace this url. Deleting the value will remove it from footer.
feedburner_url: https://feedburner.google.com/fb/a/mailverify?uri=wenhaiz&loc=en_US

# footer details. Deleting the value would remove it from footer.
github_username:  wenhaiz
email: wenhaiz.me@qq.com
weibo_username: wenhai2015
copyright_name: wenhaiz
# instagram_name: wenhaiz_
rss : false
# facebook_username:  shikherverma42
# stackoverflow_username: 6764571/shikher-verma
# twitter_username : shikherverma42
# linkedin_username : shikherverma42
# keybase_username : shikherverma

# used for portfolio on home page
# collections:
#   - portfolio

# 需要配置 tzinfo-data
timezone: Asia/Shanghai 

# used to estimate reading time
wpm: 100

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 4000
permalink: /:title

# jekyll-paginate. for paginating blog posts.
paginate: 6
paginate_path: "page:num"

# gem dependencies
plugins: [jekyll-paginate, jekyll-feed, jekyll-gist,jekyll-seo-tag]
