# Site settings
name: "赵文海"
title: "赵文海"
description: "一个持续创作的人"
baseurl: ""
url: ""
email: "wenhaiz.me@gmail.com"
lang: en-GB
encoding: utf-8
timezone: Asia/Shanghai

# Permalinks & pagination
permalink: pretty
paginate: 10
paginate_path: /blog/page:num/
excerpt_separator: <!--more-->

# Social footer links
github: "wenhaiz"

# Markdown & assets
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: /assets/css/_sass
  style: compressed

# HTML compression toggle
compress_html:
  clippings: [html,div,p,ul,td,h1,h2,h3,h4,link,meta,footer,nav,img,header,hr,br,head,style,li,ul,ol,time,main,script,title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

include:
  - _pages

exclude:
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - screenshot.png
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank

collections:
  posts:
    output: true
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      excerpt_separator: <!--more-->
